const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.TALLY_NODE_MODULES + '/playwright');
const output = 'artifacts'; fs.mkdirSync(output, { recursive: true });
const url = 'http://127.0.0.1:4173';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, acceptDownloads: true });
  const page = await context.newPage();
  const errors = []; const external = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', req => { if (/^https?:/.test(req.url()) && !req.url().startsWith(url)) external.push(req.url()); });
  const text = (value) => page.getByText(value, { exact: true });
  const shot = (name) => page.screenshot({ path: output + '/' + name + '.png' });
  const db = () => page.evaluate(() => JSON.parse(localStorage.getItem('nice-tally.ledger.v1')));
  const nav = async (name) => { await page.locator('.nav-item').filter({ hasText: name }).click(); };
  await page.goto(url); await page.locator('.welcome-start').waitFor();
  await page.locator('.welcome-start').click();
  assert.equal((await db()).records.length, 0);
  await page.locator('.nav-add').click();
  await page.locator('.person-name-input input').fill('小林');
  await page.locator('.amount-input input').fill('12.30');
  await page.locator('.field-input input').fill('周末咖啡馆');
  await page.locator('.note-input textarea').fill('本地存储测试');
  await text('添加往来对象').click();
  await page.locator('.person-name-input input').nth(1).fill('小陈');
  await page.locator('.direction-toggle').nth(1).click();
  await page.locator('.amount-input input').nth(1).fill('20.60');
  await shot('edit');
  await text('保存记录').click(); await text('记录详情').waitFor();
  let stored = await db(); assert.equal(stored.records.length, 1); assert.equal(stored.records[0].people[0].cents, -1230); assert.equal(stored.records[0].people[1].cents, 2060);
  await shot('detail');
  await page.reload(); await text('本月总览').waitFor();
  assert.equal((await db()).records[0].place, '周末咖啡馆');
  assert.match(await page.locator('.net-number').innerText(), /8\.30/);
  await nav('记录'); await page.locator('.search-input input').fill('小陈'); assert.equal(await page.locator('.activity-row').count(), 1);
  await page.locator('.activity-row').click(); await page.locator('.header-actions').getByText('编辑', { exact: true }).click();
  await page.locator('.amount-input input').first().fill('10.60'); await text('保存记录').click(); await text('记录详情').waitFor();
  assert.equal((await db()).records.length, 1); assert.equal((await db()).records[0].people[0].cents, -1060);
  await page.locator('.detail-actions').getByText('复制', { exact: true }).click(); await text('保存记录').click(); await text('记录详情').waitFor();
  assert.equal((await db()).records.length, 2);
  await page.locator('.detail-actions').getByText('删除', { exact: true }).click(); await page.locator('.uni-modal-dialog__action--confirm').click();
  await text('活动记录').waitFor(); assert.equal((await db()).records.length, 1);
  await nav('首页'); await page.locator('.nav-add').click(); await page.locator('.person-name-input input').fill('草稿联系人');
  await page.locator('.bottom-actions').getByText('保存草稿', { exact: true }).click(); await text('本月总览').waitFor();
  assert.equal((await db()).drafts.length, 1); await page.locator('.draft-banner').click();
  assert.equal(await page.locator('.person-name-input input').inputValue(), '草稿联系人');
  await page.locator('.amount-input input').fill('5.00'); await text('保存记录').click(); await text('记录详情').waitFor();
  assert.equal((await db()).drafts.length, 0); assert.equal((await db()).records.length, 2);
  await page.locator('.header > .icon-button').click(); await nav('统计'); await page.waitForTimeout(400); await shot('stats-real');
  await nav('我的'); await text('数据管理').click(); await text('备份数据').click();
  const downloadPromise = page.waitForEvent('download'); await text('保存到文件').click(); const download = await downloadPromise;
  await download.saveAs(output + '/browser-backup.json'); const exported = JSON.parse(fs.readFileSync(output + '/browser-backup.json', 'utf8'));
  assert.equal(exported.records.length, 2); assert.equal(exported.preferences.pinHash, '');
  await page.locator('.header > .icon-button').click(); await text('恢复数据').click();
  await page.locator('.transfer-textarea textarea').fill('{broken'); await text('检查并恢复').click();
  await page.getByText(/备份无效/).waitFor(); assert.equal((await db()).records.length, 2);
  await page.locator('.transfer-textarea textarea').fill(JSON.stringify(exported)); await text('检查并恢复').click(); await page.locator('.uni-modal-dialog__action--confirm').click(); await text('本月总览').waitFor();
  assert.equal((await db()).records.length, 2);
  await nav('我的'); await text('主题模式').click(); await text('深色模式').click(); await page.locator('.app-shell.dark').waitFor();
  await nav('首页'); await shot('dark'); await page.reload(); await page.locator('.app-shell.dark').waitFor();
  await nav('我的'); await text('应用锁').click();
  const enterPin = async (pin) => { for (const digit of pin) await page.locator('.key').filter({ has: page.getByText(digit, { exact: true }) }).click(); await page.waitForTimeout(350); };
  await enterPin('246810'); await text('再次输入密码').waitFor(); await enterPin('246810');
  await text('设置').waitFor(); stored = await db(); assert.equal(stored.preferences.pinHash.length, 64); assert.notEqual(stored.preferences.pinHash, '246810');
  await page.reload(); await text('输入密码').waitFor(); assert.equal(await page.locator('.overview-card').count(), 0); await shot('lock');
  await enterPin('000000'); await text('密码不正确，请重试').waitFor(); assert.equal(await page.locator('.overview-card').count(), 0);
  await enterPin('246810'); await text('本月总览').waitFor();
  await page.evaluate(() => navigator.serviceWorker.ready); await context.setOffline(true); await page.reload(); await text('输入密码').waitFor(); await enterPin('246810'); await text('本月总览').waitFor(); await page.locator('.nav-add').click(); await page.locator('.person-name-input input').fill('离线记录'); await page.locator('.amount-input input').fill('0.29'); await text('保存记录').click(); await text('记录详情').waitFor();
  assert.equal((await db()).records.length, 3); await context.setOffline(false);
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  console.log('PASS browser: create/edit/copy/delete/draft/search/reload/charts/export/import/theme/lock/offline; no external network requests.');
  await context.close();
  const demo = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 }); const dp = await demo.newPage();
  dp.on('pageerror', e => errors.push(e.message)); await dp.goto(url); await dp.getByText('先体验示例账本', { exact: true }).click();
  await dp.getByText('本月总览', { exact: true }).waitFor(); await dp.screenshot({ path: output + '/home.png' });
  await dp.locator('.nav-item').filter({ hasText: '统计' }).click(); await dp.waitForTimeout(500); await dp.screenshot({ path: output + '/statistics.png' });
  await dp.locator('.nav-item').filter({ hasText: '我的' }).click(); await dp.screenshot({ path: output + '/settings.png' });
  await dp.getByText('往来对象分析', { exact: true }).click(); await dp.screenshot({ path: output + '/people.png' });
  await dp.locator('.header > .icon-button').click(); await dp.getByText('数据管理', { exact: true }).click(); await dp.screenshot({ path: output + '/data.png' });
  await dp.setViewportSize({ width: 320, height: 720 }); await dp.locator('.header > .icon-button').click(); await dp.locator('.nav-item').filter({ hasText: '首页' }).click(); await dp.screenshot({ path: output + '/mobile-320.png' });
  assert.equal(await dp.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.deepEqual(errors, []); await browser.close();
  console.log('PASS visual captures at 390px and overflow check at 320px.');
})().catch(error => { console.error(error); process.exit(1); });


